# Generated by Django 4.2.4 on 2023-09-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetailsModel',
            fields=[
                ('Emp_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Emp_FName', models.CharField(max_length=30)),
                ('Emp_LName', models.CharField(max_length=30)),
                ('Emp_Dob', models.DateField()),
                ('Emp_Add', models.CharField(max_length=40)),
                ('Emp_Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
    ]
